package com.ljw.webservice_cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-04-09T21:10:54.865+08:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://service.webservice_cxf.ljw.com/", name = "ICalculateService")
public interface ICalculateService {

    @WebMethod
    @RequestWrapper(localName = "add", targetNamespace = "http://service.webservice_cxf.ljw.com/", className = "com.ljw.webservice_cxf.service.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://service.webservice_cxf.ljw.com/", className = "com.ljw.webservice_cxf.service.AddResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int add(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2
    );
}
